package com.exchange.designsystem.theme.color

import androidx.compose.ui.graphics.Color

internal val primaryDark = Color(0xFFFFC72C)
internal val onPrimaryDark = Color(0xFF3E2A00)
internal val primaryContainerDark = Color(0xFF5A4000)
internal val onPrimaryContainerDark = Color(0xFFFFE39F)
internal val secondaryDark = Color(0xFF39444D)
internal val onSecondaryDark = Color(0xFFECECEC)
internal val secondaryContainerDark = Color(0xFF2B333A)
internal val onSecondaryContainerDark = Color(0xFFBEC8CE)
internal val tertiaryDark = Color(0xFF39A169)
internal val onTertiaryDark = Color(0xFF00391F)
internal val tertiaryContainerDark = Color(0xFF004D31)
internal val onTertiaryContainerDark = Color(0xFFBFF5D2)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF1A1A1A)
internal val onBackgroundDark = Color(0xFFECECEC)
internal val surfaceDark = Color(0xFF1A1A1A)
internal val onSurfaceDark = Color(0xFFECECEC)
internal val surfaceVariantDark = Color(0xFF42474E)
internal val onSurfaceVariantDark = Color(0xFFC2C7CF)
internal val outlineDark = Color(0xFF8C9198)
internal val outlineVariantDark = Color(0xFF42474E)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFECECEC)
internal val inverseOnSurfaceDark = Color(0xFF2D3135)
internal val inversePrimaryDark = Color(0xFFF0B90B)
internal val surfaceDimDark = Color(0xFF1A1A1A)
internal val surfaceBrightDark = Color(0xFF36393E)
internal val surfaceContainerLowestDark = Color(0xFF121212)
internal val surfaceContainerLowDark = Color(0xFF181818)
internal val surfaceContainerDark = Color(0xFF202020)
internal val surfaceContainerHighDark = Color(0xFF272727)
internal val surfaceContainerHighestDark = Color(0xFF2D2D2D)
