package com.exchange.designsystem.theme.color

import androidx.compose.ui.graphics.Color

internal val primaryLight = Color(0xFFF0B90B)
internal val onPrimaryLight = Color(0xFF000000)
internal val primaryContainerLight = Color(0xFFFFE39F)
internal val onPrimaryContainerLight = Color(0xFF3F2E00)
internal val secondaryLight = Color(0xFF242D34)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFF39444D)
internal val onSecondaryContainerLight = Color(0xFFB3BCC3)
internal val tertiaryLight = Color(0xFF39A169)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFBFF5D2)
internal val onTertiaryContainerLight = Color(0xFF00210E)
internal val errorLight = Color(0xFFD32F2F)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFCDD2)
internal val onErrorContainerLight = Color(0xFF68000A)
internal val backgroundLight = Color(0xFFFFFFFF)
internal val onBackgroundLight = Color(0xFF242D34)
internal val surfaceLight = Color(0xFFFFFFFF)
internal val onSurfaceLight = Color(0xFF242D34)
internal val surfaceVariantLight = Color(0xFFE0E0E0)
internal val onSurfaceVariantLight = Color(0xFF5A6268)
internal val outlineLight = Color(0xFF9E9E9E)
internal val outlineVariantLight = Color(0xFFCFCFCF)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF242D34)
internal val inverseOnSurfaceLight = Color(0xFFF2F2F2)
internal val inversePrimaryLight = Color(0xFFF0B90B)
internal val surfaceDimLight = Color(0xFFFAFAFA)
internal val surfaceBrightLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF7F7F7)
internal val surfaceContainerLight = Color(0xFFECECEC)
internal val surfaceContainerHighLight = Color(0xFFE6E6E6)
internal val surfaceContainerHighestLight = Color(0xFFDCDCDC)
